spring:
  application:
    name: springbootwebtutorial

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:/D/Downloads/db
    username: sushantDB
    password: Sushant123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
